import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "./colors";
import { FONTS } from "./fonts";

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: COLORS.background,
	},
	backgroundImageStyle: {
		opacity: 0.045,
		resizeMode: "contain",
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.background,
	},
	tabContainer: {
		paddingHorizontal: 16,
		paddingTop: 12,
		paddingBottom: 4,
	},
	segmentedButtons: {
		borderRadius: 8,
	},
	activeTabButton: {
		backgroundColor: COLORS.primary,
	},
	inactiveTabButton: {
		backgroundColor: COLORS.white,
	},
	list: {
		padding: 16,
	},
	card: {
		marginBottom: 16,
		backgroundColor: COLORS.white,
		borderRadius: 12,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 8,
		elevation: 2,
		borderLeftWidth: 4,
		borderLeftColor: COLORS.primary,
	},
	announcementCard: {
		borderLeftColor: COLORS.primary,
	},
	badgeRow: {
		flexDirection: "row",
		marginBottom: 6,
	},
	newsBadge: {
		fontSize: 10,
		fontFamily: FONTS.bold,
		color: COLORS.primary,
		backgroundColor: COLORS.primaryLight,
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 4,
	},
	announcementBadge: {
		fontSize: 10,
		fontFamily: FONTS.bold,
		color: COLORS.primary,
		backgroundColor: COLORS.primaryLight,
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 4,
	},
	cardTitle: {
		fontSize: 18,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginBottom: 4,
	},
	date: {
		color: COLORS.textLight,
		fontSize: 12,
		marginBottom: 12,
		fontFamily: FONTS.regular,
	},
	sender: {
		color: COLORS.textLight,
		fontSize: 12,
		fontFamily: FONTS.semiBold,
		marginBottom: 12,
	},
	content: {
		color: COLORS.textDark,
		lineHeight: 20,
		fontSize: 14,
		fontFamily: FONTS.regular,
	},
	emptyContainer: {
		padding: 32,
		alignItems: "center",
	},
	emptyText: {
		color: COLORS.textLight,
		fontSize: 15,
		fontFamily: FONTS.regular,
	},
	guestContainer: {
		flex: 1,
		justifyContent: "center",
		padding: 24,
	},
	guestCard: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		padding: 16,
		elevation: 4,
	},
	guestContent: {
		alignItems: "center",
	},
	guestTitle: {
		color: COLORS.primary,
		fontFamily: FONTS.bold,
		fontSize: 20,
		marginBottom: 8,
	},
	guestDescription: {
		textAlign: "center",
		color: COLORS.textLight,
		marginBottom: 20,
		fontSize: 14,
		lineHeight: 20,
		fontFamily: FONTS.regular,
	},
	guestButton: {
		backgroundColor: COLORS.primary,
		width: "100%",
		borderRadius: 8,
	},
	guestButtonLabel: {
		fontFamily: FONTS.bold,
		color: COLORS.white,
	},

	// Stylizacja dla wyróżnionego (featured) newsa
	featuredCard: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		overflow: "hidden",
		elevation: 3,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.08,
		shadowRadius: 12,
		borderWidth: 1,
		borderColor: COLORS.border,
	},
	featuredCover: {
		width: "100%",
		height: 200,
	},
	featuredImageContainer: {
		position: "relative",
		width: "100%",
		height: 200,
	},
	featuredOverlay: {
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 80,
	},
	featuredBadgesRow: {
		position: "absolute",
		top: 12,
		left: 12,
		right: 12,
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		zIndex: 2,
	},
	featuredContent: {
		padding: 16,
	},
	featuredBadge: {
		fontSize: 11,
		fontFamily: FONTS.bold,
		color: COLORS.white,
		backgroundColor: COLORS.primary,
		paddingHorizontal: 10,
		paddingVertical: 3,
		borderRadius: 20,
		overflow: "hidden",
	},
	featuredBadgeSecondary: {
		fontSize: 10,
		fontFamily: FONTS.bold,
		color: COLORS.white,
		backgroundColor: "rgba(15, 23, 42, 0.75)",
		paddingHorizontal: 10,
		paddingVertical: 3,
		borderRadius: 20,
		overflow: "hidden",
	},
	featuredTitle: {
		fontSize: 20,
		fontFamily: FONTS.extraBold,
		color: COLORS.textDark,
		marginTop: 6,
		marginBottom: 4,
		lineHeight: 26,
	},
	featuredDateRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
	},
	featuredDate: {
		color: COLORS.textLight,
		fontSize: 12,
		fontFamily: FONTS.semiBold,
		marginLeft: 4,
	},
	featuredContentText: {
		color: COLORS.textDark,
		lineHeight: 22,
		fontSize: 14,
		fontFamily: FONTS.regular,
	},

	// Stylizacja dla małych newsów w stylu Flashscore
	smallCard: {
		backgroundColor: COLORS.white,
		borderRadius: 14,
		elevation: 2,
		overflow: "hidden",
		borderWidth: 1,
		borderColor: COLORS.border,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 6,
	},
	horizontalRow: {
		flexDirection: "row",
		padding: 12,
		alignItems: "center",
	},
	smallCover: {
		width: 86,
		height: 86,
		borderRadius: 10,
		overflow: "hidden",
		backgroundColor: COLORS.border,
	},
	smallCardTextContent: {
		flex: 1,
		marginLeft: 14,
		justifyContent: "center",
	},
	smallBadgeRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 4,
	},
	smallNewsBadge: {
		fontSize: 10,
		fontFamily: FONTS.bold,
		color: COLORS.primary,
		backgroundColor: COLORS.primaryLight,
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 6,
		overflow: "hidden",
	},
	smallCardTitle: {
		fontSize: 15,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		lineHeight: 20,
		marginBottom: 4,
	},
	smallCardDateRow: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 2,
	},
	smallCardDate: {
		color: COLORS.textLight,
		fontSize: 11,
		fontFamily: FONTS.regular,
		marginLeft: 4,
	},

	// Dialog dla szczegółów aktualności
	dialogTitle: {
		fontSize: 18,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
	},
	dialogContent: {
		paddingTop: 0,
	},
	dialogScroll: {
		maxHeight: 520,
	},
	dialogCover: {
		height: 180,
		marginBottom: 12,
		width: "100%",
	},
	dialogDate: {
		color: COLORS.textLight,
		fontSize: 12,
		marginBottom: 8,
		fontFamily: FONTS.semiBold,
	},
	dialogText: {
		color: COLORS.textDark,
		fontSize: 15,
		lineHeight: 24,
		fontFamily: FONTS.regular,
	},

	// Formularz dodawania postów
	fab: {
		position: "absolute",
		right: 20,
		bottom: 18,
		backgroundColor: COLORS.primary,
		borderRadius: 28,
		elevation: 6,
		shadowColor: COLORS.primary,
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.35,
		shadowRadius: 6,
	},
	emojiBarContainer: {
		marginBottom: 8,
		marginTop: 4,
	},
	emojiBarLabel: {
		fontSize: 11,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginBottom: 4,
	},
	emojiRowScroll: {
		flexDirection: "row",
		paddingVertical: 2,
	},
	emojiGridChip: {
		width: 34,
		height: 34,
		borderRadius: 8,
		backgroundColor: COLORS.white,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 6,
		borderWidth: 1,
		borderColor: COLORS.border,
		elevation: 1,
	},
	emojiText: {
		fontSize: 16,
	},
	dropdownSelector: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: COLORS.white,
		borderWidth: 1,
		borderColor: COLORS.border,
		borderRadius: 10,
		paddingHorizontal: 14,
		paddingVertical: 12,
		marginTop: 4,
	},
	dropdownSelectorText: {
		flex: 1,
		fontSize: 14,
		fontFamily: FONTS.semiBold,
		color: COLORS.textDark,
		marginLeft: 10,
	},
	dropdownOption: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 8,
		marginBottom: 4,
	},
	dropdownOptionActive: {
		backgroundColor: COLORS.primaryLight,
	},
	dropdownOptionText: {
		flex: 1,
		fontSize: 14,
		fontFamily: FONTS.regular,
		color: COLORS.textDark,
		marginLeft: 12,
	},
	dropdownOptionTextActive: {
		fontFamily: FONTS.bold,
		color: COLORS.primary,
	},
	dialogScrollForm: {
		maxHeight: Dimensions.get("window").height * 0.72,
	},
	formInput: {
		marginBottom: 12,
		backgroundColor: COLORS.white,
	},
	formButton: {
		backgroundColor: COLORS.primary,
	},
	switchRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: 8,
		marginBottom: 12,
		paddingVertical: 4,
	},
	switchLabel: {
		fontSize: 14,
		color: COLORS.textDark,
		flex: 1,
		paddingRight: 10,
		fontFamily: FONTS.regular,
	},
	pickerContainer: {
		marginTop: 12,
		marginBottom: 8,
	},
	pickerLabel: {
		fontSize: 14,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginBottom: 6,
	},
	teamChipsScroll: {
		flexDirection: "row",
		paddingVertical: 4,
	},
	teamChip: {
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		backgroundColor: COLORS.background,
		marginRight: 8,
		borderWidth: 1,
		borderColor: COLORS.border,
	},
	teamChipActive: {
		backgroundColor: COLORS.primaryLight,
		borderColor: COLORS.primary,
	},
	teamChipText: {
		fontSize: 12,
		color: COLORS.textDark,
		fontFamily: FONTS.regular,
	},
	teamChipTextActive: {
		color: COLORS.primary,
		fontFamily: FONTS.bold,
	},

	// Upload i podgląd zdjęć
	uploadZone: {
		borderWidth: 1.5,
		borderColor: COLORS.border,
		borderStyle: "dashed",
		borderRadius: 12,
		padding: 16,
		alignItems: "center",
		backgroundColor: COLORS.background,
		marginBottom: 16,
		marginTop: 4,
	},
	uploadZoneTitle: {
		fontSize: 13,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginBottom: 2,
	},
	uploadZoneSubtitle: {
		fontSize: 11,
		color: COLORS.textLight,
		marginBottom: 12,
		fontFamily: FONTS.regular,
	},
	uploadZoneButtons: {
		flexDirection: "row",
		justifyContent: "space-between",
		width: "100%",
	},
	uploadZoneBtn: {
		flex: 0.47,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: COLORS.white,
		borderWidth: 1,
		borderColor: COLORS.border,
		borderRadius: 8,
		paddingVertical: 10,
		elevation: 1,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.05,
		shadowRadius: 1,
	},
	uploadZoneBtnText: {
		fontSize: 12,
		fontFamily: FONTS.bold,
		color: COLORS.primary,
		marginLeft: 6,
	},
	imagePreviewContainer: {
		width: "100%",
		height: 160,
		borderRadius: 12,
		overflow: "hidden",
		marginBottom: 16,
		marginTop: 4,
		position: "relative",
	},
	imagePreview: {
		width: "100%",
		height: "100%",
		resizeMode: "cover",
	},
	removeImageButton: {
		position: "absolute",
		top: 10,
		right: 10,
		backgroundColor: "rgba(239, 68, 68, 0.9)",
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		elevation: 2,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.25,
		shadowRadius: 3.84,
	},
	removeImageText: {
		color: COLORS.white,
		fontSize: 12,
		fontFamily: FONTS.bold,
		marginLeft: 4,
	},
	uploadingContainer: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		marginBottom: 16,
	},
	uploadingText: {
		fontSize: 13,
		color: COLORS.textDark,
		marginLeft: 8,
		fontFamily: FONTS.regular,
	},

	// Stylizacja opcji (switches)
	settingsGroup: {
		backgroundColor: COLORS.background,
		borderRadius: 12,
		borderWidth: 1,
		borderColor: COLORS.border,
		marginBottom: 16,
		overflow: "hidden",
	},
	settingRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 12,
	},
	settingTextContainer: {
		flex: 1,
		paddingRight: 10,
	},
	settingLabel: {
		fontSize: 13,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
	},
	settingDescription: {
		fontSize: 11,
		color: COLORS.textLight,
		marginTop: 1,
		fontFamily: FONTS.regular,
	},

	// Layouty modalów i przycisków
	dialogContainer: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		width: "92%",
		alignSelf: "center",
		paddingVertical: 4,
	},
	formActionsRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		paddingHorizontal: 24,
		paddingBottom: 16,
		paddingTop: 8,
	},
	cancelBtn: {
		flex: 0.47,
		borderRadius: 8,
		borderColor: COLORS.border,
	},
	submitBtn: {
		flex: 0.47,
		borderRadius: 8,
		backgroundColor: COLORS.primary,
	},

	// Kontenery gestów swipe do edycji/usuwania
	swipeActionsContainerFeatured: {
		flexDirection: "row",
		width: 140,
		height: "100%",
		overflow: "hidden",
		borderTopRightRadius: 12,
		borderBottomRightRadius: 12,
	},
	swipeActionsContainerSmall: {
		flexDirection: "row",
		width: 140,
		height: "100%",
		overflow: "hidden",
		borderTopRightRadius: 12,
		borderBottomRightRadius: 12,
	},
	swipeActionBtn: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		height: "100%",
	},
	editActionBtn: {
		backgroundColor: COLORS.primary,
	},
	deleteActionBtn: {
		backgroundColor: "#ef4444",
		borderTopRightRadius: 12,
		borderBottomRightRadius: 12,
	},
	swipeActionText: {
		color: COLORS.white,
		fontSize: 11,
		fontFamily: FONTS.bold,
		marginTop: 4,
	},

	// League Table Styles
	tableScrollContent: {
		padding: 16,
		paddingBottom: 32,
	},
	tableCard: {
		backgroundColor: COLORS.white,
		borderRadius: 16,
		elevation: 4,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.08,
		shadowRadius: 12,
		borderWidth: 1,
		borderColor: COLORS.border,
		overflow: "hidden",
	},
	tableTitle: {
		fontSize: 16,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		textAlign: "center",
		marginBottom: 2,
		marginTop: 8,
	},
	tableSubtitle: {
		fontSize: 12,
		fontFamily: FONTS.regular,
		color: COLORS.textLight,
		textAlign: "center",
		marginBottom: 16,
	},
	tableHeaderRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 8,
		paddingHorizontal: 12,
		backgroundColor: "#f8fafc",
		borderBottomWidth: 1,
		borderBottomColor: COLORS.border,
	},
	tableBodyRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderBottomWidth: 1,
		borderBottomColor: "#f1f5f9",
	},
	tableRowHighlight: {
		backgroundColor: "#eff6ff",
		borderBottomColor: "#bfdbfe",
	},
	tableCol: {
		textAlign: "center",
		fontSize: 13,
	},
	colPos: {
		width: 24,
	},
	colName: {
		flex: 2,
		paddingLeft: 8,
	},
	colM: {
		width: 32,
	},
	colB: {
		width: 56,
	},
	colPkt: {
		width: 38,
	},
	headerText: {
		fontFamily: FONTS.bold,
		color: COLORS.textLight,
		fontSize: 12,
	},
	bodyText: {
		fontFamily: FONTS.regular,
		color: COLORS.textDark,
	},
	bodyTextBold: {
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
	},
	textHighlight: {
		color: COLORS.primary,
		fontFamily: FONTS.regular,
	},
	textHighlightBold: {
		color: COLORS.primary,
		fontFamily: FONTS.bold,
	},

	// Custom Pill Tab Switcher
	customTabContainer: {
		paddingHorizontal: 16,
		paddingTop: 12,
		paddingBottom: 6,
	},
	customTabWrapper: {
		flexDirection: "row",
		backgroundColor: "#F1F5F9",
		borderRadius: 14,
		padding: 4,
		borderWidth: 1,
		borderColor: "#E2E8F0",
	},
	customTabItem: {
		flex: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 9,
		borderRadius: 10,
	},
	customTabItemActive: {
		backgroundColor: COLORS.primary,
		elevation: 3,
		shadowColor: COLORS.primary,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.25,
		shadowRadius: 4,
	},
	customTabText: {
		fontSize: 13,
	},
	customTabTextActive: {
		fontFamily: FONTS.bold,
		color: COLORS.white,
	},
	customTabTextInactive: {
		fontFamily: FONTS.semiBold,
		color: COLORS.textLight,
	},

	// Multi-image upload preview
	multiImageRow: {
		flexDirection: "row",
		marginBottom: 16,
		marginTop: 4,
	},
	multiImageThumbWrapper: {
		width: 86,
		height: 86,
		borderRadius: 10,
		marginRight: 10,
		position: "relative",
		overflow: "visible",
	},
	multiImageThumb: {
		width: 86,
		height: 86,
		borderRadius: 10,
	},
	multiImageRemoveBadge: {
		position: "absolute",
		top: -6,
		right: -6,
		backgroundColor: "#ef4444",
		width: 22,
		height: 22,
		borderRadius: 11,
		alignItems: "center",
		justifyContent: "center",
		elevation: 4,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 1 },
		shadowOpacity: 0.3,
		shadowRadius: 2,
	},
	multiImageBadgeText: {
		color: COLORS.white,
		fontSize: 11,
		fontFamily: FONTS.bold,
	},

	// Detail Modal Carousel & Reordered Title
	detailCarouselContainer: {
		width: "100%",
		height: 220,
		borderRadius: 14,
		overflow: "hidden",
		marginBottom: 14,
		backgroundColor: "#f1f5f9",
		position: "relative",
	},
	detailCarouselImage: {
		width: Dimensions.get("window").width * 0.92 - 32,
		height: 220,
		borderRadius: 14,
	},
	closeModalBtn: {
		position: "absolute",
		top: 12,
		right: 12,
		width: 34,
		height: 34,
		borderRadius: 17,
		backgroundColor: "rgba(15, 23, 42, 0.65)",
		alignItems: "center",
		justifyContent: "center",
		zIndex: 10,
	},
	detailPagination: {
		position: "absolute",
		bottom: 10,
		left: 0,
		right: 0,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	detailPaginationDot: {
		width: 7,
		height: 7,
		borderRadius: 3.5,
		backgroundColor: "rgba(255, 255, 255, 0.5)",
		marginHorizontal: 3,
	},
	detailPaginationDotActive: {
		width: 18,
		backgroundColor: COLORS.white,
		borderRadius: 4,
	},
	detailCategoryBadge: {
		alignSelf: "flex-start",
		backgroundColor: COLORS.primaryLight,
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 20,
		marginBottom: 6,
	},
	detailCategoryBadgeText: {
		color: COLORS.primary,
		fontFamily: FONTS.bold,
		fontSize: 11,
	},
	detailTitleUnderImage: {
		fontSize: 21,
		fontFamily: FONTS.extraBold,
		color: COLORS.textDark,
		marginBottom: 8,
		lineHeight: 27,
	},
	detailAuthorRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingBottom: 10,
		marginBottom: 12,
		borderBottomWidth: 1,
		borderBottomColor: COLORS.border,
	},
	detailAuthorAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		backgroundColor: COLORS.primaryLight,
		alignItems: "center",
		justifyContent: "center",
		marginRight: 10,
	},
	detailAuthorName: {
		fontSize: 13,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
	},
	detailDateText: {
		fontSize: 11,
		fontFamily: FONTS.regular,
		color: COLORS.textLight,
	},

	// Reakcje kibiców pod artykułem
	reactionsBarContainer: {
		backgroundColor: COLORS.background,
		borderRadius: 14,
		padding: 12,
		marginTop: 14,
		marginBottom: 8,
		borderWidth: 1,
		borderColor: COLORS.border,
	},
	reactionsBarLabel: {
		fontSize: 12,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginBottom: 8,
	},
	reactionsRow: {
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	reactionBtn: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: COLORS.white,
		paddingHorizontal: 10,
		paddingVertical: 6,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: COLORS.border,
	},
	reactionBtnActive: {
		backgroundColor: COLORS.primaryLight,
		borderColor: COLORS.primary,
	},
	reactionEmoji: {
		fontSize: 16,
	},
	reactionCount: {
		fontSize: 12,
		fontFamily: FONTS.bold,
		color: COLORS.textDark,
		marginLeft: 4,
	},
	reactionCountActive: {
		color: COLORS.primary,
	},
	youtubeWatchBtn: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#FF0000",
		borderRadius: 12,
		paddingVertical: 12,
		paddingHorizontal: 16,
		marginVertical: 12,
		elevation: 3,
		shadowColor: "#FF0000",
		shadowOffset: { width: 0, height: 3 },
		shadowOpacity: 0.3,
		shadowRadius: 5,
	},
	youtubeWatchBtnText: {
		color: COLORS.white,
		fontSize: 13,
		fontFamily: FONTS.bold,
		marginLeft: 8,
	},
});
