-- GKS Strzegowo: bezpieczny model czatu dla Supabase
-- Skrypt jest niedestrukcyjny dla istniejących wiadomości:
-- stare kolumny recipient_id i channel zostają, ale nowa aplikacja już ich nie używa.

create extension if not exists pgcrypto;

create table if not exists public.chat_conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('direct', 'staff')),
  conversation_key text not null unique,
  title text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  conversation_id uuid not null references public.chat_conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

-- Jeśli chat_messages już istnieje, zostanie rozszerzone bez kasowania danych.
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.chat_conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  sender_name text,
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_messages
  add column if not exists conversation_id uuid references public.chat_conversations(id) on delete cascade;

alter table public.chat_messages
  add column if not exists sender_name text;

create index if not exists chat_members_user_id_idx
  on public.chat_members(user_id);

create index if not exists chat_messages_conversation_created_at_idx
  on public.chat_messages(conversation_id, created_at);

-- Jeden stały pokój sztabu. Dostęp nie jest oparty o ręczną listę członków,
-- tylko o aktualną rolę admin/coach w profiles.
insert into public.chat_conversations (kind, conversation_key, title)
values ('staff', 'staff:gks-strzegowo', 'Sztab GKS Strzegowo')
on conflict (conversation_key) do update
set kind = excluded.kind,
    title = excluded.title;

-- Czy bieżący użytkownik może rozpocząć rozmowę 1:1 z podaną osobą?
create or replace function public.can_chat_with(p_other_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  with me as (
    select id, role::text as role, team_id
    from public.profiles
    where id = auth.uid()
  ), other_user as (
    select id, role::text as role, team_id
    from public.profiles
    where id = p_other_user_id
  )
  select coalesce((
    select case
      when me.id = other_user.id then false

      -- Administrator może pisać indywidualnie do rodzica i zawodnika.
      when me.role = 'admin' and other_user.role in ('parent', 'player') then true
      when me.role in ('parent', 'player') and other_user.role = 'admin' then true

      -- Trener widzi wyłącznie rodziców/zawodników ze swoich drużyn.
      when me.role = 'coach' and other_user.role in ('parent', 'player') then exists (
        select 1
        from public.teams t
        where t.coach_id = me.id
          and t.id = other_user.team_id
      )

      -- Rodzic/zawodnik widzi trenera przypisanego do jego team_id.
      when me.role in ('parent', 'player') and other_user.role = 'coach' then exists (
        select 1
        from public.teams t
        where t.coach_id = other_user.id
          and t.id = me.team_id
      )

      else false
    end
    from me cross join other_user
  ), false);
$$;

-- Lista kontaktów jest generowana w bazie. Klient nie pobiera całej tabeli profiles.
create or replace function public.list_chat_contacts()
returns table (
  id uuid,
  first_name text,
  last_name text,
  role text,
  team_name text
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    p.id,
    p.first_name,
    p.last_name,
    p.role::text,
    t.name::text as team_name
  from public.profiles p
  left join public.teams t on t.id = p.team_id
  where public.can_chat_with(p.id)
  order by p.last_name nulls last, p.first_name nulls last;
$$;

-- Tworzenie czatu 1:1 wyłącznie przez kontrolowane RPC.
create or replace function public.get_or_create_direct_chat(p_other_user_id uuid)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_me uuid := auth.uid();
  v_key text;
  v_conversation_id uuid;
begin
  if v_me is null then
    raise exception 'Musisz być zalogowany' using errcode = '42501';
  end if;

  if not public.can_chat_with(p_other_user_id) then
    raise exception 'Brak uprawnień do tej rozmowy' using errcode = '42501';
  end if;

  v_key := 'direct:' || least(v_me::text, p_other_user_id::text)
    || ':' || greatest(v_me::text, p_other_user_id::text);

  insert into public.chat_conversations (kind, conversation_key, title, created_by)
  values ('direct', v_key, 'Rozmowa prywatna', v_me)
  on conflict (conversation_key) do update
    set conversation_key = excluded.conversation_key
  returning id into v_conversation_id;

  insert into public.chat_members (conversation_id, user_id)
  values
    (v_conversation_id, v_me),
    (v_conversation_id, p_other_user_id)
  on conflict do nothing;

  return v_conversation_id;
end;
$$;

create or replace function public.get_staff_conversation()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_conversation_id uuid;
begin
  if not exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role::text in ('admin', 'coach')
  ) then
    raise exception 'Brak dostępu do czatu sztabu' using errcode = '42501';
  end if;

  select id into v_conversation_id
  from public.chat_conversations
  where conversation_key = 'staff:gks-strzegowo';

  return v_conversation_id;
end;
$$;

-- Funkcja używana przez RLS. Dla staff sprawdza aktualną rolę, dzięki czemu
-- każdy przyszły trener automatycznie dostanie dostęp po zmianie roli.
create or replace function public.can_access_chat(p_conversation_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.chat_conversations c
    where c.id = p_conversation_id
      and (
        (
          c.kind = 'staff'
          and exists (
            select 1
            from public.profiles p
            where p.id = auth.uid()
              and p.role::text in ('admin', 'coach')
          )
        )
        or
        (
          c.kind = 'direct'
          and exists (
            select 1
            from public.chat_members me_member
            where me_member.conversation_id = c.id
              and me_member.user_id = auth.uid()
          )
          -- Samo dawne członkostwo nie wystarcza. Relacja musi nadal być
          -- dozwolona, np. trener nadal musi prowadzić drużynę rodzica.
          and exists (
            select 1
            from public.chat_members other_member
            where other_member.conversation_id = c.id
              and other_member.user_id <> auth.uid()
              and public.can_chat_with(other_member.user_id)
          )
        )
      )
  );
$$;

-- Nazwa nadawcy jest ustawiana przez bazę, a treść jest czyszczona i limitowana.
create or replace function public.prepare_chat_message()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text;
begin
  if auth.uid() is not null then
    new.sender_id := auth.uid();
  end if;

  new.content := btrim(new.content);
  if char_length(new.content) < 1 or char_length(new.content) > 2000 then
    raise exception 'Wiadomość musi mieć od 1 do 2000 znaków';
  end if;

  select nullif(btrim(concat_ws(' ', p.first_name, p.last_name)), '')
  into v_name
  from public.profiles p
  where p.id = new.sender_id;

  new.sender_name := coalesce(v_name, 'Użytkownik');
  return new;
end;
$$;

drop trigger if exists prepare_chat_message_trigger on public.chat_messages;
create trigger prepare_chat_message_trigger
before insert or update of content on public.chat_messages
for each row execute function public.prepare_chat_message();

alter table public.chat_conversations enable row level security;
alter table public.chat_members enable row level security;
alter table public.chat_messages enable row level security;

-- Usuwamy wyłącznie polityki trzech tabel czatu i zakładamy kompletne od nowa.
do $$
declare
  policy_row record;
begin
  for policy_row in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('chat_conversations', 'chat_members', 'chat_messages')
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_row.policyname,
      policy_row.schemaname,
      policy_row.tablename
    );
  end loop;
end $$;

create policy "chat_conversations_select_allowed"
on public.chat_conversations
for select
to authenticated
using (public.can_access_chat(id));

create policy "chat_members_select_own"
on public.chat_members
for select
to authenticated
using (user_id = auth.uid());

create policy "chat_messages_select_allowed"
on public.chat_messages
for select
to authenticated
using (
  conversation_id is not null
  and public.can_access_chat(conversation_id)
);

create policy "chat_messages_insert_allowed"
on public.chat_messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and conversation_id is not null
  and public.can_access_chat(conversation_id)
);

revoke all on public.chat_conversations from anon;
revoke all on public.chat_members from anon;
revoke all on public.chat_messages from anon;

revoke all on public.chat_conversations from authenticated;
revoke all on public.chat_members from authenticated;
revoke all on public.chat_messages from authenticated;

grant select on public.chat_conversations to authenticated;
grant select on public.chat_members to authenticated;
grant select, insert on public.chat_messages to authenticated;

-- Gdy id wiadomości jest identity/serial, rola authenticated potrzebuje
-- dostępu do przypisanej sekwencji. Blok działa też, gdy istniejąca tabela ma UUID.
do $$
declare
  message_id_sequence text;
begin
  select pg_get_serial_sequence('public.chat_messages', 'id')
  into message_id_sequence;

  if message_id_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to authenticated',
      message_id_sequence
    );
  end if;
end $$;

revoke all on function public.can_chat_with(uuid) from public;
revoke all on function public.list_chat_contacts() from public;
revoke all on function public.get_or_create_direct_chat(uuid) from public;
revoke all on function public.get_staff_conversation() from public;
revoke all on function public.can_access_chat(uuid) from public;

grant execute on function public.can_chat_with(uuid) to authenticated;
grant execute on function public.list_chat_contacts() to authenticated;
grant execute on function public.get_or_create_direct_chat(uuid) to authenticated;
grant execute on function public.get_staff_conversation() to authenticated;
grant execute on function public.can_access_chat(uuid) to authenticated;

-- Realtime dla nowych wiadomości. Blok nie zgłosi błędu, jeśli tabela już jest dodana.
do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
end $$;
