CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Aktualności są widoczne dla zalogowanych" 
ON public.news FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Tylko admin może dodawać/edytować/usuwać aktualności" 
ON public.news FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    )
);
