CREATE TABLE IF NOT EXISTS public.trainings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    coach TEXT NOT NULL,
    time TEXT NOT NULL,          -- np. 'Poniedziałek 16:00-17:30'
    location TEXT NOT NULL,      -- np. 'Boisko główne'
    max_capacity INT DEFAULT 15, -- maksymalna liczba osób
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.trainings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Treningi są widoczne dla zalogowanych" 
ON public.trainings FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Tylko admin może dodawać/edytować/usuwać treningi" 
ON public.trainings FOR ALL 
TO authenticated 
USING (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    )
);
