CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    training_id BIGINT NOT NULL REFERENCES public.trainings(id) ON DELETE CASCADE,
    booking_date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (user_id, training_id, booking_date) -- zabezpieczenie przed podwójną rezerwacją tego samego dnia
);

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Użytkownicy widzą własne rezerwacje, admin widzi wszystkie" 
ON public.bookings FOR SELECT 
TO authenticated 
USING (
    auth.uid() = user_id OR 
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    )
);

CREATE POLICY "Zalogowani użytkownicy mogą rezerwować dla siebie" 
ON public.bookings FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Użytkownicy mogą odwołać własną rezerwację" 
ON public.bookings FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);
